# Generated by Django 3.2.7 on 2021-11-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_exam', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now=True)),
                ('number_of_times', models.IntegerField(default=0)),
                ('maker_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=500)),
                ('answer_a', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_answer_wrong', models.CharField(max_length=200)),
                ('result_of_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizi.exam')),
                ('result_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.user')),
            ],
        ),
    ]
