# Generated by Django 3.2.7 on 2021-10-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_img',
        ),
    ]
