# Generated by Django 3.2.7 on 2021-10-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211022_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_discription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=500),
        ),
    ]
