# Generated by Django 3.2.7 on 2021-11-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
