# Generated by Django 3.2.7 on 2021-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.CharField(default='/media/background_item.png', max_length=50),
        ),
    ]
